# Generated by Django 5.0.7 on 2024-07-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_product_deal_discount_percentage_deal_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
