# Generated by Django 5.0.7 on 2024-07-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
