# Generated by Django 5.0.7 on 2024-07-21 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_cart_id_alter_cart_date_added_and_more'),
        ('promotions', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promotions.deal'),
        ),
    ]
